### ISSUE TITLE
Initial testing for rAudio1

### ISSUE THREAD

**Issue by ceejayemm** [rern/rAudio-1#2]
Rern

Downloaded the RPI Zero version for testing as requested. Booted new SD card, which included a 'wifi' file configured for my wireless network and got into system to start configuration. Message on screen that MPD wasn't running. Applied Updates (20201213), OK, Restored backup of previous RA+Re6. Changed Host Name back to rAudio, disabled I2S settings, turned on Bluetooth. Reboot required. RPI rebooted but could not then find wireless network and rAudio not available. I will reflash the SD card and try again but this time will not restore backup file to see if that makes a difference.

Chris

**Comment by ceejayemm** [comment]
Rern

Can't do a manual config for the following reasons:

When adding a Source, either CIFS or NFS, the slashes are removed from the share path.

In the System page the new Sub Menu from RA+Re6 is missing.

On System page, changing the Sound Profile is not saved.

Can't open MPD page - no sound cards found. Correct, was going to test RPi Zero with Bluetooth speakers, so enabled Bluetooth and turned off I2S setting. Cannot change Audio setting. All on System page.

Not sure I can go much further at the moment.

Chris

**Comment by ceejayemm** [comment]
Rern

Further info

I can't disable the I2S setting , I do not have such a device available for my PI Zero at the moment so was going to try Bluetooth instead.

If I enable Bluetooth, then on the Networks page I can search for BT devices and find my printer, my laptop but not my Soundsticks which are right next to my PI and discoverable (can be found by main RA+Re6 system). I inadvertantly paired with my printer and now can't unpair it. Boot log shows an whole load of errors such as:

Dec 12 09:45:28 rAudio bluetoothd[295]: src/main.c:parse_controller_config() Key file does not have key “LEMaxConnectionInterval” in group “Controller”

for a variety of key names.

Chris

**Comment by ceejayemm** [comment]
@rern

Update

I have applied the 202012131 update (yesterday) and refreshed the install from the 'main' branch this morning. The issue with the slashes being removed from Sources path seems to have been resolved and I can mount my normal NFS based music store.

I still cannot set the I2S setting to 'Disabled' but I have set it to one of the AdaFruit DAC devices which now at least allows me to access the MPD page and set the output device to Headphones.

Both of the above now allow me to update the Library with my music..

The remaining problem relates to Bluetooth. My  problem is that I only have a PI Zero W to test this release.  This device doesn't have any audio output and I don't have a DAC device I can use with it for output at the moment. I do however have a set of Harmon Kardon Soundstick speakers which allow Bluetooth access. I have enabled Bluetooth in System and can search for devices in Networks but the Soundsticks are not found. I have also tried the bluetoothctl utility from the console and this doesn't find them either. Both do find my other RA based PIs which have Bluetooth turned on and my printer. I think the problem might be that the Soundstick use the low power bluetooth setting when idle.  The Soundsticks can be found from a PI3B+ running RA+Re6. Is there a difference between the Bluetooth implementation in the RAudio/RA images for PI 0/1 and PI3 ?

If we can get the speakers recognised how do I then control volume etc as they don't seem to turn up in the MPD output device setting and hence available to the volume control. Is this something that will spring into life once the speakers are correctly paired ?

Chris

**Comment by rern** [comment]
Hi Chris,

Thank you for your reports.

After ketnel 5.4.72, RPi Zero on-board audio will be available only when connected with a HDMI device.

Bluetooth volume is normally controlled from other devices.

Image files have been updated. Please download from the previous links and try again.

rern

**Comment by ceejayemm** [comment]
Rern

Thanks for this info. The removal of the on-board audio from PI Zero is not a problem for me IF we can get the Bluetooth connection sorted out.

I have re-flashed the SD card with the latest image and have been able to set up my sources. The I2S setting is off (presumably disabled). I have set Bluetooth on and made it discoverable (not sure I need to do this but I did) and searched in Networks for my Soundsticks – still not found!  Also the MPD page is not available in this configuration, I am not sure it needs to be but there are options on there I would need, like FFMpeg, which I can’t get at due to MPD Not Running / No Soundcards found. If all I want to use is the Bluetooth connection how can I do this ?

Thanks

Chris



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ceejayemm** [comment]
@rern 

I think I have solved the problem with the Bluetooth speakers.  It appears that although other devices can see the Soundsticks in their semi-dormant status, RAudio needs them to be fully powered up and in full discovery mode. Once I did this then they could be discovered by RAudio and appeared in the Network section.

The other issue, 'MPD not running' and the MPD page not being available, were solved when I connected the PI Zero with RAudio installed to a HDMI monitor (not something I really wanted to do). After a reboot the MPD page was available with HDMI Audio selected in the Audio Output Devices. AND Bluetooth output just happened (?).

Would it be possible to not have to have the HDMI screen/cable attached and for Bluetooth Audio to be selectable in the Audio Output Device list. The Bluetooth details are available in the Status option:

bind_to_address        "0.0.0.0"
db_file                "/srv/http/data/mpd/mpd.db"
music_directory        "/mnt/MPD"
playlist_directory     "/var/lib/mpd/playlists"
replaygain             "off"
state_file             "/srv/http/data/mpd/mpdstate"
user                   "mpd"

input {
	plugin         "curl"
}

decoder {
	plugin         "ffmpeg"
	enabled        "yes"
}

resampler {
	plugin         "soxr"
	quality        "very high"
}

audio_output {
	name           "On-board - HDMI"
	device         "hw:0,0"
	type           "alsa"
	auto_resample  "no"
	auto_format    "no"
	mixer_type     "none"
}

audio_output {
	name           "SoundSticks Wireless"
	device         "bluealsa:DEV=0C:A6:94:39:48:C1,PROFILE=a2dp"
	type           "alsa"
	mixer_type     "software"
}

So could this be used to populate the Audio Output Devices list and be selectable? This would make Bluetooth connection set up a lot more obvious and a whole lot more understandable. Keep the existing Bluetooth setting / discovery but add this last step to complete the MPD setup. It would then work like adding other I2S devices that might have been used previously.

Chris

**Comment by rern** [comment]
Hi Chris,

Once paired, power on/off devices or connect/disconnect will do it all automatically.

rern

**Comment by ceejayemm** [comment]
Rern

The speakers will ONLY re-pair if they are in the full awake mode. Even in this case they don't seem to reconnect correctly / fully and won't provide any output.  I am not sure what might help to understand this but the following is what I have seen, this is after a recent reboot:

Networks:

Bluetooth <Green Dot> Soundsticks Wireless
Wi-Fi <Green Dot>  192.168.86.179 >> 192.168.86.1  CMHomeNET


Devices:  **<No Bluetooth device seen>**

**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7


Hardware Mixers  **(No Bluetooth mixers)**

card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
Simple mixer control 'HDMI',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback 0 [96%] [0.00dB] [on]
  
Status:

? mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/system/mpd.service; disabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/mpd.service.d
             +-override.conf
     Active: active (running) since Mon 2020-12-14 10:13:59 UTC; 7h ago
       Docs: man:mpd(1)
             man:mpd.conf(5)
   Main PID: 947 (mpd)
      Tasks: 7 (limit: 926)
     CGroup: /system.slice/mpd.service
             +-947 /usr/bin/mpd --no-daemon

Dec 14 10:16:07 rAudio mpd[947]: ffmpeg/http: Cannot reuse HTTP connection for different host: bbcfmt-ic-52451b00-03e5ea-ashlsuklivebbcfmt.s.loris.llnwd.net:-1 != as-hls-uk-live.bbcfmt.s.llnwi.net:-1
Dec 14 10:16:07 rAudio mpd[947]: ffmpeg/hls: keepalive request failed for 'http://as-hls-uk-live.bbcfmt.s.llnwi.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio=320000.norewind.m3u8' with error: 'Invalid argument' when parsing playlist
Dec 14 10:16:14 rAudio mpd[947]: ffmpeg/http: Cannot reuse HTTP connection for different host: bbcfmt-ic-52451b00-03e5ea-ashlsuklivebbcfmt.s.loris.llnwd.net:-1 != as-hls-uk-live.bbcfmt.s.llnwi.net:-1
Dec 14 10:16:14 rAudio mpd[947]: ffmpeg/hls: keepalive request failed for 'http://as-hls-uk-live.bbcfmt.s.llnwi.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio=320000.norewind.m3u8' with error: 'Invalid argument' when parsing playlist
Dec 14 10:16:14 rAudio mpd[947]: player: played "http://as-hls-uk-live.bbcfmt.s.llnwi.net/pool_904/live/uk/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio=320000.norewind.m3u8"
Dec 14 10:16:14 rAudio mpd[947]: D: bluealsa-pcm.c:349: /org/bluealsa/hci0/dev_0C_A6_94_39_48_C1/a2dpsrc/sink: Stopping
Dec 14 10:16:14 rAudio mpd[947]: D: bluealsa-pcm.c:129: /org/bluealsa/hci0/dev_0C_A6_94_39_48_C1/a2dpsrc/sink: IO thread cleanup
Dec 14 10:16:14 rAudio mpd[947]: D: bluealsa-pcm.c:349: /org/bluealsa/hci0/dev_0C_A6_94_39_48_C1/a2dpsrc/sink: Stopping
Dec 14 10:16:14 rAudio mpd[947]: D: bluealsa-pcm.c:432: /org/bluealsa/hci0/dev_0C_A6_94_39_48_C1/a2dpsrc/sink: Freeing HW
Dec 14 10:16:14 rAudio mpd[947]: D: bluealsa-pcm.c:385: /org/bluealsa/hci0/dev_0C_A6_94_39_48_C1/a2dpsrc/sink: Closing

Let me know if you need any further info from me.

Chris
